### ISSUE TITLE
Ошибки в коде

### ISSUE THREAD

**Issue by ArthurDavletov** [LuigiVampa92/vk_photos#1]
Сначала была следующая ошибка в синтаксисе
`$ python photos.py
  File "/data/data/com.termux/files/home/programs/vk_photos/photos.py", line 133
    print 'collecting %s of %s' % (str(i + 1), str(fave_iterations))
          ^
SyntaxError: invalid syntax`
Ладно, поставил скобки (я не спец по Python, лишь сделал наугад)
Затем появилась новая ошибка (не новая, а другая):
`$ python photos.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/programs/vk_photos/photos.py", line 6, in <module>
    from urllib import urlopen
ImportError: cannot import name 'urlopen' from 'urllib' (/data/data/com.termux/files/usr/lib/python3.9/urllib/__init__.py)`
У меня Python 3.9.0. Termux

**Comment by LuigiVampa92** [comment]
Скрипт был изначально написан под python2, но ничего сильно зависящего от версии там не было. Пофиксил импорты, проверил, работает одинаково как на 2 так и на 3

Скачайте заново и проверьте, должно работать

**Comment by ArthurDavletov** [comment]
> Скрипт был изначально написан под python2, но ничего сильно зависящего от версии там не было. Пофиксил импорты, проверил, работает одинаково как на 2 так и на 3
> 
> Скачайте заново и проверьте, должно работать

Да, теперь работает, спасибо)
