### ISSUE TITLE
Ошибка.

### ISSUE THREAD

**Issue by D0n-A** [LuigiVampa92/vk_photos#2]
Здравствуйте! После успешной авторизации и формирования списка фотографий - последняя команда не загружает их. И буквально все фото в файле errors.txt. Проверено несколько раз и с разными группами.

**Comment by LuigiVampa92** [comment]
Доброе утро. Списки фотографий вполне могут не собираться если у залогиненого аккаунта нет доступа к альбому, но файлы по полученным статическим ссылкам должны загружаться без проблем. Можете пожалуйста скинуть пример подобной группы? 

Также могу предположить что не скачивало файлы из за временного плохого соединения. Как вариант можно заново дёрнуть download указав файл со списком ссылок. Те, что не были скачаны скрипт попробует скачать ещё раз

**Comment by D0n-A** [comment]
Да, спасибо. Теперь все нормально. Закрываю.
