### ISSUE TITLE
Проблема с поиском фотографий

### ISSUE THREAD

**Issue by a1ex-997** [LuigiVampa92/vk_photos#3]
Здравствуйте! На днях скачал vk_photos для Kali Linux, делал всё по инструкции, авторизовался под собой, указал id моей 2 страницы в ВКонтакте(там было много моих фотографий, которые я удалил и теперь хочу восстановить). Нажимаю Enter(для поиска) и он("vk_photos") находит только те фотографии, которые и так есть у меня на странице. Подскажите что нужно сделать чтобы он нашёл мои удалённые фотографии?!

**Comment by LuigiVampa92** [comment]
Добрый день. К сожалению, удалённые фото скачать не получится. Скрипт просто автоматизирует то что можно сделать руками в браузере. Если фото удалены и доступа к ним нет, то и этот скрипт загрузить их не сможет

**Comment by a1ex-997** [comment]
Понял, спасибо!)
